language: rust
env:
  global:
    - PROJECT_NAME: blockstack-sshkey
    - BINARY_NAME: blockstack-sshkey
    - RUST_BACKTRACE: full
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
cache: cargo
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed.
    - "/^\\d+\\.\\d+\\.\\d+.*$/"
install: ci/install.sh
before_deploy: ci/prepare_release.sh
deploy:
  provider: releases
  api_key:
    secure: "fSfooM0g6y0yOwaIWpSQD6ieg0BFYqevd6uYgv339NVFuCriBRWlMwUkHrnDwhiWC1eYdtURRCceQouuC+K3Lofet4TBk4FHHGcDimNqih8/Jq7YvSgo37kWn7m+IKuk6wLlExZgLrwRPBLzxoS06Nv07i88YKLy4vwk2XtRuljCEFPgEuVtpXsgak6rXKwEOF0jbf9iIfrvWmiRmPr4H+gtpPKWcqttKC4B8MZ3pdlTKXUHdA6uEGP6TJjc+h/EzZ0HCMEhTCsDlFTiNpM2VW1CzFP/N0yvBduEac3oqf6B9GScEA8jQJQ6XX63VN93+nz2Pbuaj1uCPhC84tVVkqYeP4qKsqWYhqM+qQOg/KbpA//t9azfaDcACtScQg+a48qr5vepYAet+KjVSJHrsJQeWfzy0dUC1u1roP3lJMrRzZDWCtRlHEoR3EzudpZIWIgqVCFBazxidpl/pDZ+ltigTcRdM7y2H96QfZny2txcAuld0uc9++cCy6aPdpc9b3QpnAd8kbZP6dIiltcsx1Yao8v55664r0VzlViWZkkfyzu8sDCsWqu+/WHUWlIuHcEnT7o7NGaQxQENM2rBFGPl4CaWf0rAE+NSkp6AQXxGfDqs6Er66zQ2qM7usTdgZPzRgdTh1h6mLNXbe9b4DOi37kSZO3YxRAMy5K+6BMc="
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: colindean/blocktap-sshkey
    condition: $TRAVIS_RUST_VERSION = nightly
    branch: master  # i guess we do need this after all?
    tags: true
