[package]
name = "blockstack-sshkey"
version = "0.2.2-alpha.0"
authors = ["Colin Dean <git@cad.cx>"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false #inhibit publishing to crates.io

[dependencies]
serde_json = "1.0"
reqwest = "0.9.0"

[dev-dependencies]
cargo-release = "*"
